/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import modeloBeans.BeansCliente;
import modeloBeans.ModeloTabela;
import modeloConexao.ConexaoBD;
import modeloDao.DaoCliente;


public class FormCliente extends javax.swing.JFrame {

        BeansCliente mod = new BeansCliente();
        ConexaoBD conex = new ConexaoBD();
        DaoCliente control = new DaoCliente();
        
        int flag = 0;
        
        
    public FormCliente() {
        initComponents();
        
                        // coloca uma figura na barra de título da janela
        URL url = this.getClass().getResource("/Imagens/salao.png");
        Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(imagemTitulo);
        
       // preencherTabela("select * from clientes order by nome_cliente");

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonNovo = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jLabelTitulo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabelNomeCompleto = new javax.swing.JLabel();
        jTextFieldNomeCompleto = new javax.swing.JTextField();
        jLabelApelido = new javax.swing.JLabel();
        jTextFieldApelido = new javax.swing.JTextField();
        jLabelEmail = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabelTelefone = new javax.swing.JLabel();
        jTextFieldTelefone = new javax.swing.JTextField();
        jLabelAniversario = new javax.swing.JLabel();
        jTextFieldAniversario = new javax.swing.JTextField();
        jLabelCodigo = new javax.swing.JLabel();
        jTextFieldCodigo = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabelEndereco = new javax.swing.JLabel();
        jLabelCep = new javax.swing.JLabel();
        jTextFieldCep = new javax.swing.JTextField();
        jLabelRua = new javax.swing.JLabel();
        jTextFieldRua = new javax.swing.JTextField();
        jLabelNumero = new javax.swing.JLabel();
        jTextFieldNumero = new javax.swing.JTextField();
        jLabelBairro = new javax.swing.JLabel();
        jTextFieldBairro = new javax.swing.JTextField();
        jLabelCidade = new javax.swing.JLabel();
        jTextFieldCidade = new javax.swing.JTextField();
        jLabelEstado = new javax.swing.JLabel();
        jComboBoxEstado = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCliente = new javax.swing.JTable();
        jTextFieldPesquisa = new javax.swing.JTextField();
        jButtonPesquisar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButtonNovo.setText("Novo");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.setEnabled(false);
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setEnabled(false);
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonEditar.setText("Editar");
        jButtonEditar.setEnabled(false);
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.setEnabled(false);
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jLabelTitulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelTitulo.setText("CADASTRO DE CLIENTES");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelNomeCompleto.setText("Nome completo: ");

        jTextFieldNomeCompleto.setEnabled(false);

        jLabelApelido.setText("Apelido:");

        jTextFieldApelido.setEnabled(false);

        jLabelEmail.setText("E-mail:");

        jTextFieldEmail.setEnabled(false);

        jLabelTelefone.setText("Telefone:");

        jTextFieldTelefone.setEnabled(false);

        jLabelAniversario.setText("Aniversário:");

        jTextFieldAniversario.setEnabled(false);

        jLabelCodigo.setText("Código:");

        jTextFieldCodigo.setEnabled(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelEndereco.setText("Endereço");

        jLabelCep.setText("Cep:");

        jTextFieldCep.setEnabled(false);

        jLabelRua.setText("Rua:");

        jTextFieldRua.setEnabled(false);

        jLabelNumero.setText("Número:");

        jTextFieldNumero.setEnabled(false);

        jLabelBairro.setText("Bairro:");

        jTextFieldBairro.setEnabled(false);

        jLabelCidade.setText("Cidade:");

        jTextFieldCidade.setEnabled(false);

        jLabelEstado.setText("Estado:");

        jComboBoxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        jComboBoxEstado.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabelCep))
                            .addComponent(jLabelBairro))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jTextFieldCep, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)
                                .addComponent(jLabelRua)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldRua))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jTextFieldBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelCidade)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldCidade, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabelNumero)
                                .addGap(10, 10, 10)
                                .addComponent(jTextFieldNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabelEstado)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBoxEstado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(22, 22, 22))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelEndereco)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelEndereco)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCep)
                    .addComponent(jTextFieldCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelRua)
                    .addComponent(jTextFieldRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNumero)
                    .addComponent(jTextFieldNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelBairro)
                    .addComponent(jLabelCidade)
                    .addComponent(jTextFieldCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEstado)
                    .addComponent(jComboBoxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jTableCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableClienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableCliente);

        jButtonPesquisar.setText("Pesquisar");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelNomeCompleto)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(23, 23, 23)
                                    .addComponent(jLabelEmail))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(15, 15, 15)
                                    .addComponent(jLabelAniversario)))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldNomeCompleto, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                                    .addComponent(jTextFieldEmail))
                                .addComponent(jTextFieldAniversario, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelTelefone, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelApelido, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addComponent(jLabelCodigo))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextFieldTelefone)
                                .addComponent(jTextFieldApelido)
                                .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextFieldPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(jButtonPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldNomeCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelApelido)
                        .addComponent(jTextFieldApelido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelNomeCompleto))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTelefone)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEmail))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAniversario)
                    .addComponent(jTextFieldAniversario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCodigo)
                    .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPesquisar))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                    .addComponent(jButtonEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(317, Short.MAX_VALUE)
                .addComponent(jLabelTitulo)
                .addGap(245, 245, 245))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jButtonNovo)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSalvar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCancelar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonEditar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonExcluir))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabelTitulo)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(782, 651));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        
        flag = 1;
        jButtonSalvar.setEnabled(true);
        jTextFieldNomeCompleto.setEnabled(true);
        jTextFieldApelido.setEnabled(true);
        jTextFieldEmail.setEnabled(true);
        jTextFieldTelefone.setEnabled(true);
        jTextFieldAniversario.setEnabled(true);
        jTextFieldCep.setEnabled(true);
        jTextFieldRua.setEnabled(true);
        jTextFieldNumero.setEnabled(true);
        jTextFieldBairro.setEnabled(true);
        jTextFieldCidade.setEnabled(true);
        jComboBoxEstado.setEnabled(true);
        jTextFieldNomeCompleto.setText("");
        jTextFieldApelido.setText("");
        jTextFieldEmail.setText("");
        jTextFieldCodigo.setText("");
        jTextFieldTelefone.setText("");
        jTextFieldAniversario.setText("");
        jTextFieldCep.setText("");
        jTextFieldNumero.setText("");
        jTextFieldRua.setText("");
        jTextFieldCidade.setText("");
        jTextFieldBairro.setText("");
        jButtonEditar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        jTextFieldPesquisa.setEnabled(false);
        jButtonPesquisar.setEnabled(false);
        
    }//GEN-LAST:event_jButtonNovoActionPerformed

    public void preencherTabela(String sql){
        
        ArrayList dados = new ArrayList();
        //String [] colunas = new String []{"nome_funcionario","area_funcionario","cpf_funcionario","cod_funcionario"};
        String [] colunas = new String []{"ID","Nome","Apelido","E-mail","Telefone","Aniversario"};
        conex.conexao();
        conex.executaSql(sql);
        
        try{
            conex.rs.first();
            do{
                //dados.add(new Object[]{conex.rs.getString("nome_funcionario"),conex.rs.getString("area_funcionario"),conex.rs.getInt("cpf_funcionario"),conex.rs.getInt("cod_funcionario")});
                dados.add(new Object[]{conex.rs.getInt("id_cliente"),conex.rs.getString("nome_cliente"),conex.rs.getString("nome_apelido"),conex.rs.getString("email_cliente"),conex.rs.getString("telefone_cliente"),conex.rs.getString("aniversario_cliente")});
                
            }while(conex.rs.next());
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(rootPane, "Busque outro Cliente para atualizar tabela!");
            return;
        }
        ModeloTabela modelo = new ModeloTabela(dados, colunas);
        jTableCliente.setModel(modelo);
        jTableCliente.getColumnModel().getColumn(0).setPreferredWidth(30);
        jTableCliente.getColumnModel().getColumn(0).setResizable(false);
        jTableCliente.getColumnModel().getColumn(1).setPreferredWidth(200);
        jTableCliente.getColumnModel().getColumn(1).setResizable(false);
        jTableCliente.getColumnModel().getColumn(2).setPreferredWidth(200);
        jTableCliente.getColumnModel().getColumn(2).setResizable(false);
        jTableCliente.getColumnModel().getColumn(3).setPreferredWidth(200);
        jTableCliente.getColumnModel().getColumn(3).setResizable(false);
        jTableCliente.getColumnModel().getColumn(4).setPreferredWidth(200);
        jTableCliente.getColumnModel().getColumn(4).setResizable(false);
        jTableCliente.getColumnModel().getColumn(5).setPreferredWidth(200);
        jTableCliente.getColumnModel().getColumn(5).setResizable(false);
        jTableCliente.getColumnModel().getColumn(6).setPreferredWidth(200);
        jTableCliente.getColumnModel().getColumn(6).setResizable(false);
        jTableCliente.getTableHeader().setReorderingAllowed(false);
        jTableCliente.setAutoResizeMode(jTableCliente.AUTO_RESIZE_OFF);
        jTableCliente.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        
        //conex.desconecta();
    }
    

    
    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
        
        mod.setPesquisa(jTextFieldPesquisa.getText());
        BeansCliente model = control.buscaCliente(mod);
        jTextFieldNomeCompleto.setText(model.getNome_completo());
        jTextFieldApelido.setText(model.getNome_apelido());
        jTextFieldCodigo.setText(String.valueOf(model.getCod_cliente()));
        jTextFieldEmail.setText(model.getEmail());
        jTextFieldTelefone.setText(String.valueOf(model.getTelefone()));
        jTextFieldAniversario.setText(model.getAniversario());
        jTextFieldRua.setText(model.getRua());
        jTextFieldNumero.setText(String.valueOf(model.getNumero()));
        jTextFieldCep.setText(String.valueOf(model.getCep()));
        jTextFieldBairro.setText(model.getBairro());
        jTextFieldCidade.setText(model.getCidade());
        jComboBoxEstado.setSelectedItem(model.getEstado());
        
        preencherTabela("select *from clientes where nome_cliente like'%"+mod.getPesquisa()+"%'");
        
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        
        jTextFieldNomeCompleto.setEnabled(!true);
        jButtonSalvar.setEnabled(!true);
        jButtonCancelar.setEnabled(!true);
        jButtonNovo.setEnabled(true);
        jButtonEditar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        jTextFieldPesquisa.setEnabled(true);
        jButtonPesquisar.setEnabled(true);
        jTextFieldNomeCompleto.setText("");
        jTextFieldApelido.setText("");
        jTextFieldPesquisa.setText("");
        jTextFieldCodigo.setText("");
        jTextFieldEmail.setText("");
        jTextFieldTelefone.setText("");
        jTextFieldAniversario.setText("");
        jTextFieldRua.setText("");
        jTextFieldNumero.setText("");
        jTextFieldCep.setText("");
        jTextFieldBairro.setText("");
        jTextFieldCidade.setText("");
        
        
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        
        flag = 2;
        jTextFieldNomeCompleto.setEnabled(true);
        jComboBoxEstado.setEnabled(true);
        jButtonSalvar.setEnabled(true);
        jButtonCancelar.setEnabled(true);
        jButtonEditar.setEnabled(false);
        jButtonNovo.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        
        
        
        
        
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        
        int resposta = 0;
        resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente excluir?");
        if(resposta == JOptionPane.YES_OPTION){
            mod.setCod_cliente(Integer.parseInt(jTextFieldCodigo.getText()));
            control.Excluir(mod);
            jTextFieldNomeCompleto.setText("");
            jTextFieldCodigo.setText("");
            jTextFieldApelido.setText("");
            jTextFieldPesquisa.setText("");
            jTextFieldEmail.setText("");
            jTextFieldTelefone.setText("");
            jTextFieldAniversario.setText("");
            jTextFieldRua.setText("");
            jTextFieldNumero.setText("");
            jTextFieldCep.setText("");
            jTextFieldBairro.setText("");
            jTextFieldCidade.setText("");
            jButtonEditar.setEnabled(false);
            jTextFieldNomeCompleto.setEnabled(false);
            jButtonExcluir.setEnabled(false);
            jComboBoxEstado.setEnabled(false);
            jButtonSalvar.setEnabled(false);
            jButtonCancelar.setEnabled(false);
            jButtonNovo.setEnabled(true);
            jButtonCancelar.setEnabled(false);
           preencherTabela("select * from clientes order by nome_cliente");
        }
    }//GEN-LAST:event_jButtonExcluirActionPerformed

        
        
        
    private void jTableClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableClienteMouseClicked
       
        String nome_cliente = ""+jTableCliente.getValueAt(jTableCliente.getSelectedRow(), 1);
        conex.conexao();
        conex.executaSql("select * from clientes where nome_cliente='"+nome_cliente+"'"); 
            try {
                conex.rs.first();
                jTextFieldCodigo.setText(String.valueOf(conex.rs.getInt("id_cliente")));
                jTextFieldNomeCompleto.setText(conex.rs.getString("nome_cliente"));
                jTextFieldApelido.setText(conex.rs.getString("nome_apelido"));
                jTextFieldEmail.setText(conex.rs.getString("email_cliente"));
                jTextFieldTelefone.setText(String.valueOf(conex.rs.getInt("telefone_cliente")));
                jTextFieldAniversario.setText(conex.rs.getString("aniversario_cliente"));
                jTextFieldRua.setText(conex.rs.getString("rua_cliente"));
                jTextFieldNumero.setText(String.valueOf(conex.rs.getInt("numero_cliente")));
                jTextFieldCep.setText(String.valueOf(conex.rs.getInt("cep_cliente")));
                jTextFieldBairro.setText(conex.rs.getString("bairro_cliente"));
                jTextFieldCidade.setText(conex.rs.getString("cidade_cliente"));
                jComboBoxEstado.setSelectedItem(conex.rs.getString("estado_cliente"));
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Erro ao selecionar os dados!");
            }
        
        //conex.desconecta();
        
        jButtonEditar.setEnabled(true);
        jButtonExcluir.setEnabled(true);

    }//GEN-LAST:event_jTableClienteMouseClicked

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        if(jTextFieldNomeCompleto.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Preencha o nome para continuar!");
            jTextFieldNomeCompleto.requestFocus();
        }
        if(flag == 1){
            //preencherTabela("select * from clientes order by nome_cliente");
            mod.setNome_completo(jTextFieldNomeCompleto.getText());
            mod.setNome_apelido(jTextFieldApelido.getText());
            mod.setEmail(jTextFieldEmail.getText());
            mod.setTelefone( Integer.parseInt( jTextFieldTelefone.getText() ) );
            mod.setAniversario((String)jTextFieldAniversario.getText());
            mod.setRua(jTextFieldRua.getText());
            mod.setNumero(Integer.parseInt(jTextFieldNumero.getText()));
            mod.setCep(Integer.parseInt(jTextFieldCep.getText()));
            mod.setBairro(jTextFieldBairro.getText());
            mod.setCidade(jTextFieldCidade.getText());
            mod.setEstado( (String) jComboBoxEstado.getSelectedItem());
            control.Salvar(mod);
            jTextFieldNomeCompleto.setText("");
            jTextFieldApelido.setText("");
            jTextFieldCodigo.setText("");
            jTextFieldEmail.setText("");
            jTextFieldTelefone.setText("");
            jTextFieldAniversario.setText("");
            jTextFieldRua.setText("");
            jTextFieldNumero.setText("");
            jTextFieldCep.setText("");
            jTextFieldBairro.setText("");
            jTextFieldCidade.setText("");
            jTextFieldNomeCompleto.setEnabled(false);
            jTextFieldApelido.setEnabled(false);
            jTextFieldCodigo.setEnabled(false);
            jTextFieldEmail.setEnabled(false);
            jTextFieldTelefone.setEnabled(false);
            jTextFieldAniversario.setEnabled(false);
            jTextFieldRua.setEnabled(false);
            jTextFieldNumero.setEnabled(false);
            jTextFieldCep.setEnabled(false);
            jTextFieldBairro.setEnabled(false);
            jTextFieldCidade.setEnabled(false);
            jComboBoxEstado.setEnabled(false);
            jButtonSalvar.setEnabled(false);
            jButtonCancelar.setEnabled(false);
            preencherTabela("select * from clientes order by nome_cliente");
        }
        else{
            jTextFieldNomeCompleto.setEnabled(!false);
            jTextFieldApelido.setEnabled(true);
            jTextFieldEmail.setEnabled(true);
            jTextFieldTelefone.setEnabled(true);
            jTextFieldAniversario.setEnabled(true);
            jTextFieldRua.setEnabled(true);
            jTextFieldNumero.setEnabled(true);
            jTextFieldCep.setEnabled(true);
            jTextFieldBairro.setEnabled(true);
            jTextFieldCidade.setEnabled(true);
            jComboBoxEstado.setEnabled(true);
            jButtonSalvar.setEnabled(true);
            jButtonCancelar.setEnabled(true);
            mod.setCod_cliente((Integer.parseInt(jTextFieldCodigo.getText())));
            mod.setNome_completo(jTextFieldNomeCompleto.getText());
            mod.setNome_apelido(jTextFieldApelido.getText());
            mod.setEmail(jTextFieldEmail.getText());
            mod.setTelefone( Integer.parseInt( jTextFieldTelefone.getText() ) );
            mod.setAniversario(jTextFieldAniversario.getText());
            mod.setRua(jTextFieldRua.getText());
            mod.setNumero(Integer.parseInt(jTextFieldNumero.getText()));
            mod.setCep(Integer.parseInt(jTextFieldCep.getText()));
            mod.setBairro(jTextFieldBairro.getText());
            mod.setCidade(jTextFieldCidade.getText());
            mod.setEstado( (String) jComboBoxEstado.getSelectedItem());
            control.Editar(mod);
            jTextFieldNomeCompleto.setText("");
            jTextFieldApelido.setText("");
            jTextFieldCodigo.setText("");
            jTextFieldEmail.setText("");
            jTextFieldTelefone.setText("");
            jTextFieldAniversario.setText("");
            jTextFieldRua.setText("");
            jTextFieldNumero.setText("");
            jTextFieldCep.setText("");
            jTextFieldBairro.setText("");
            jTextFieldCidade.setText("");
            
            jTextFieldNomeCompleto.setEnabled(!false);
            jTextFieldApelido.setEnabled(!false);
            jTextFieldCodigo.setEnabled(false);
            jTextFieldEmail.setEnabled(!false);
            jTextFieldTelefone.setEnabled(!false);
            jTextFieldAniversario.setEnabled(!false);
            jTextFieldRua.setEnabled(!false);
            jTextFieldNumero.setEnabled(!false);
            jTextFieldCep.setEnabled(!false);
            jTextFieldBairro.setEnabled(!false);
            jTextFieldCidade.setEnabled(!false);
            jComboBoxEstado.setEnabled(!false);
            jButtonSalvar.setEnabled(!false);
            jButtonCancelar.setEnabled(!false);
            preencherTabela("select * from clientes order by nome_cliente");
        }
    }//GEN-LAST:event_jButtonSalvarActionPerformed
   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox<String> jComboBoxEstado;
    private javax.swing.JLabel jLabelAniversario;
    private javax.swing.JLabel jLabelApelido;
    private javax.swing.JLabel jLabelBairro;
    private javax.swing.JLabel jLabelCep;
    private javax.swing.JLabel jLabelCidade;
    private javax.swing.JLabel jLabelCodigo;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelEndereco;
    private javax.swing.JLabel jLabelEstado;
    private javax.swing.JLabel jLabelNomeCompleto;
    private javax.swing.JLabel jLabelNumero;
    private javax.swing.JLabel jLabelRua;
    private javax.swing.JLabel jLabelTelefone;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCliente;
    private javax.swing.JTextField jTextFieldAniversario;
    private javax.swing.JTextField jTextFieldApelido;
    private javax.swing.JTextField jTextFieldBairro;
    private javax.swing.JTextField jTextFieldCep;
    private javax.swing.JTextField jTextFieldCidade;
    private javax.swing.JTextField jTextFieldCodigo;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldNomeCompleto;
    private javax.swing.JTextField jTextFieldNumero;
    private javax.swing.JTextField jTextFieldPesquisa;
    private javax.swing.JTextField jTextFieldRua;
    private javax.swing.JTextField jTextFieldTelefone;
    // End of variables declaration//GEN-END:variables
}
